name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar remoto upstream
      run: git remote add upstream https://github.com/wppconnect-team/wa-version.git

    - name: Sincronizar com upstream
      run: git fetch upstream && git checkout main && git merge upstream/main

    - name: Empurrar alterações para o fork
      run: git push origin main

  
  
